### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by LukasRychtecky** [duct-framework/database.redis.carmine#1] opened 2018-03-15 09:37 UTC
Clojure 1.9.0
Carmine 2.17.0
Integrant 0.6.3

**Comment by agrison** [comment] 2018-06-15 07:37
Hi @weavejester can this be merged and released 😄 ?

The repl won't start as soon as I add a dependency to `duct/database.redis.carmine` due to the dependency on Clojure `1.9.0-alpha17` creating such a stacktrace.

    Error loading cider.nrepl.middleware.test: java.lang.RuntimeException: Invalid token: ::clojure.test/once-fixtures, compiling:(cider/nrepl/middleware/test.clj:106:57)
    Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: cider.nrepl.middleware.test/wrap-test in this context, compiling:(/private/var/folders/pn/jcqmh8s53hn_wtkjvlwnsv300000gn/T/form-init7502863698992055448.clj:1:9419)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7010)
        ...
    	at clojure.main.main(main.java:37)
    Caused by: java.lang.RuntimeException: Unable to resolve var: cider.nrepl.middleware.test/wrap-test in this context
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:720)

See this related CIDER issue: https://github.com/clojure-emacs/cider/issues/2081

For your information it does only break `lein repl`, `lein run` has no problem, it runs smoothly.

**Comment by agrison** [comment] 2018-06-15 07:51
Well my bad! 🤒 

In fact my whole repl was not working at all on any Clojure 1.9+ project, I updated the `cider/cider-nrepl` and `org.clojure/tools.nrepl` in my `~/.lein/profiles.clj` and it is working fine now.

    {:user {:plugins [
                       ...
                       [cider/cider-nrepl "0.17.0"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.13"]]}}

Still, if carmine could be updated to `2.18.1` it would be cool 😃

**Comment by weavejester** [comment] 2018-06-16 17:18
Fixed by d8a44e3.

**Closed as completed by weavejester** 2018-06-16 17:18 UTC
